= bespoke-title
Dan Allen <https://github.com/mojavelinux>
// Settings:
:idprefix:
:idseparator: -
ifdef::env-github[:badges:]
// Variables:
:release-version: master
// URIs:
:uri-raw-file-base: https://raw.githubusercontent.com/opendevise/bespoke-title/{release-version}

ifdef::badges[]
//image:https://img.shields.io/npm/v/bespoke-title.svg[npm package, link=https://www.npmjs.com/package/bespoke-title]
image:https://img.shields.io/travis/opendevise/bespoke-title/master.svg[Build Status (Travis CI), link=https://travis-ci.org/opendevise/bespoke-title]
endif::[]

Automatically sets the document title to match the title of the active slide in a http://markdalgleish.com/projects/bespoke.js[Bespoke.js] presentation.

== Example

http://opendevise.github.io/bespoke-title[View the demo] online.

This repository includes a demo folder the shows this plugin in action.
To view it locally, you first need to clone this repository:

 $ git clone https://github.com/opendevise/bespoke-title && cd bespoke-title

Next, install the dependencies inside the project folder using npm:

 $ npm install

Finally, visit the file [path]_demo/index.html_ in your browser to see the plugin in action.

== Download

Download the {uri-raw-file-base}/dist/bespoke-title.min.js[production mode version] or the {uri-raw-file-base}/dist/bespoke-title.js[development mode version], or use a package manager.

=== npm

 $ npm install bespoke-title

=== Bower

 $ bower install bespoke-title

== Usage

This plugin is shipped in a https://github.com/umdjs/umd[UMD format], meaning it is available as a CommonJS/AMD module or as a browser global.

For example, when using CommonJS modules:

```js
var bespoke = require('bespoke'),
  title = require('bespoke-title');

bespoke.from('.deck', [
  title()
]);
```

When using a browser global:

```js
bespoke.from('.deck', [
  bespoke.plugins.title()
]);
```

=== Options

The following options are available when registering the bespoke-title plugin:

title _(type: string, default: document.title)_::
The title of the presentation, which appears after the title of the slide in the document's title.

separator _(type: string, default: ' — ')_::
The separator to place between the slide title and the presentation title in the document's title.
No additional spaces are added to this value.

==== Options example

Here's an example showing most of the options in use:

```
bespoke.from('.deck', [
  title({ title: 'Demo', separator: ': ' })
]);
```

== Behavior

This plugin updates the document title to match the slide title when each slide is activated.
The slide title is derived from either the `data-title` attribute on the slide or, if the `data-title` attribute is absent, the first `<h1>` or `<h2>` heading in the slide.
If the `data-title` attribute is present but empty, or there is no `<h1>` or `<h2>` heading in the slide, the document title reverts back to the presentation title.

== License

http://en.wikipedia.org/wiki/MIT_License[MIT License]
